# AI Coach System Configuration

# API Configuration
api:
  anthropic:
    model: "claude-3-5-sonnet-20241022"
    max_tokens: 1000
    timeout: 30
    temperature: 0.3  # Lower for more consistent outputs
  
  openai:
    model: "gpt-4o"
    evolution_model: "gpt-4o-mini"  # Faster model for mutations
    max_tokens: 1500
    timeout: 30
    temperature: 0.7

# Data Generation Settings
data_generation:
  default_users: 50
  default_records: 10000
  days_of_history: 30
  time_acceleration: 60  # 1 real second = 60 seconds of data
  
  persona_distribution:
    developer: 0.4
    analyst: 0.3
    manager: 0.2
    designer: 0.1
  
  temporal_patterns:
    work_start_hour: 8
    work_end_hour: 18
    peak_hours: [10, 11, 14, 15]
    low_activity_hours: [8, 12, 17]

# Evolution Settings
evolution:
  population_size: 20
  generations: 50
  elite_ratio: 0.2
  crossover_probability: 0.7
  mutation_probability: 0.3
  convergence_threshold: 0.01
  
  fitness_weights:
    json_validity: 0.3
    actionability: 0.3
    consistency: 0.2
    completeness: 0.2

# Coaching Settings
coaching:
  max_daily_nudges: 3
  min_nudge_interval_minutes: 30
  confidence_threshold: 0.7
  analysis_window_minutes: 15
  
  nudge_preferences:
    max_words: 40
    preferred_tone: "friendly"
    include_metrics: true
    personalization_level: "high"
  
  effectiveness_targets:
    acceptance_rate: 0.65
    productivity_lift: 0.12
    satisfaction_lift: 0.10

# Simulation Settings
simulation:
  response_time_range: [2, 60]  # seconds
  
  context_awareness:
    enabled: true
    factors:
      - "high_focus_session"
      - "multiple_interruptions"
      - "end_of_day"
      - "meeting_heavy_day"
      - "deadline_pressure"
  
  long_term_tracking:
    enabled: true
    metrics:
      - "productivity_improvement"
      - "satisfaction_improvement"
      - "behavior_change_score"

# Logging and Output
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
output:
  save_synthetic_data: true
  save_evolution_history: true
  save_nudge_logs: true
  output_directory: "outputs"

# Performance Settings
performance:
  max_concurrent_evaluations: 5
  cache_evaluation_results: true
  batch_size: 50
  
# Experimental Features
experimental:
  adaptive_nudging: false  # Adjust nudge frequency based on user response
  multi_modal_analysis: false  # Include non-telemetry data
  predictive_coaching: false  # Anticipate issues before they occur